package com.weibo.ad.example.anno;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface AdColumn {
    /**
     * (Optional) The name of the column. Defaults to
     * the property or field name.
     */
    String columnName() default "";
    /**
     * (Optional) Whether the database column is nullable.
     */
    boolean nullable() default true;
    /**
     * (Optional) Whether the column is included in SQL INSERT
     * statements generated by the persistence provider.
     */
    boolean insertable() default true;
    /**
     * (Optional) Whether the column is included in SQL UPDATE
     * statements generated by the persistence provider.
     */
    boolean updateable() default true;
}
